---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Home Lab:
    - Homepage:
        href: http://wowehome:3000
        description: Homelab dashboard for all services and links to other services.

    - n8n:
        href: http://wowehome:5678
        description: Workflow automation tool for automating tasks and processes.
