---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- datetime:
    text_size: xl
    format:
        timeStyle: short
        hour12: true

- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    uptime: true
    refresh: 3000 # optional, in ms

- search:
    provider: google
    target: _blank
